version: '3.1'

services:

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    volumes: 
      - /db-data:/data/db


  mongo-express:
    links:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
    links:
      - mongo

  restaurants:
    build: .
    ports:
      - 8080:8080
    environment: 
      PORT: 8080
      MONGODB_CONNECTIONSTRING: mongodb://mongoadmin:mongoadmin@mongo:27017/restaurants?authSource=admin
    links:
      - mongo
